<a href="https://colab.research.google.com/github/DannyKuvonchbek/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
import pandas as pd

In [10]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford"],
    'passings': [3, 7, 2]
}

df = pd.DataFrame(mydataset)

print(df)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [11]:
df.head()

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [12]:
df.tail()

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [13]:
df.shape

(3, 2)

In [14]:
df.columns

Index(['cars', 'passings'], dtype='object')

In [15]:
df.dtypes

cars        object
passings     int64
dtype: object

In [16]:
df.describe()

       passings
count  3.000000
mean   4.000000
std    2.645751
min    2.000000
25%    2.500000
50%    3.000000
75%    5.000000
max    7.000000

In [17]:
df

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [ ]:
df.loc[0,"cars"]

'BMW'

In [18]:
df[df['passings'] > 2]

    cars  passings
0    BMW         3
1  Volvo         7

In [19]:
df.mean(numeric_only=True)

passings    4.0
dtype: float64

In [20]:
df['passings'].mean()

np.float64(4.0)

In [21]:
data_with_missing = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", None],
    'passings': [3, 7, 2, None, 4]
}

df_data = pd.DataFrame(data_with_missing)

print(df_data)

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       NaN
4   None       4.0

In [22]:
df_data.isnull()

    cars  passings
0  False     False
1  False     False
2  False     False
3  False      True
4   True     False

In [23]:
df_data.dropna()

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0

In [24]:
df_data.dropna(axis=0)

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0

In [25]:
df_data

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       NaN
4   None       4.0

In [26]:
df_data.dropna(subset=['cars'])

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       NaN

In [27]:
df_data.fillna(0)

    cars  passings
0    BMW       3.0
1  Volvo       7.0
2   Ford       2.0
3  Tesla       0.0
4      0       4.0

In [28]:
df_data.fillna({'cars': "car_name", "passings": 1})

       cars  passings
0       BMW       3.0
1     Volvo       7.0
2      Ford       2.0
3     Tesla       1.0
4  car_name       4.0

In [29]:
# Series => 1D

a = ["bwm", "tesla", "toyota"]

myvar = pd.Series(a)

print(myvar)

0       bwm
1     tesla
2    toyota
dtype: object